# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c65cb43d6133d149c75b34c5a9fd4e89d9566c141acc8ba44b36a1f56a2adb726d8bf9963c1c9de0f7d9eaded2e85e15e2b8f00ebb5340756bbdc79354612cd3

test:
  secret_key_base: 569553562fc9eca0c4c4fe559a593a6a452a4a4622b9b2f414cbca50421049f270aa7b33943bf11c839d8edf04d94412dd0cc9d40f48e33e91ce1c78af6b0256

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
